### ISSUE TITLE
Possible contradicting recommendation regarding parentheses around function calls

### ISSUE THREAD

**Issue by firoxer** [luarocks/lua-style-guide#1]
Hi!

I noticed that there is a possible contradiction in the recommendation regarding parentheses around function calls.

On line 253 (linking to the line seems to be impossible with Markdown files, sorry) it is said that parentheses around function calls should not be omitted (`Even though Lua allows it, do not omit parenthesis for functions that take a unique string literal argument`) whereas on line 730 there's a good example where the parentheses are omitted. (`local messagepack = require "messagepack"`).

Is this because the `require` function is a bit special? :)

Great style guide btw!

**Comment by hishamhm** [comment]
Thank you! 

That example was a slip because I copied it from another style guide. I'll fix it to add the parentheses. Some people treat `require` specially, but I don't like to do that because in the end of the day, it is a regular Lua function, and not a keyword like Python's `import`. :)

**Comment by firoxer** [comment]
Alright, that makes sense. Thanks!
