### ISSUE TITLE
static checker for these rules?

### ISSUE THREAD

**Issue by rwv37** [luarocks/lua-style-guide#6]
Is there a static checker for these rules? I know luacheck is mentioned in the article itself, but it doesn't seem to follow these rules (at least, not by default - I don't know if there's some option or configuration or whatever that would allow it).

**Comment by hishamhm** [comment]
I don't currently use luacheck to check for style, I use it to catch the classes of mistakes it is able to. I think some of the style rules written here are configurable in luacheck, but others are deliberately lenient and wouldn't really work with a static checker...
