### ISSUE TITLE
Trailing whitespace should not be allowed

### ISSUE THREAD

**Issue by still-dreaming-1** [luarocks/lua-style-guide#7]
This rule of the style guide should be reversed to not allow trailing whitespace:

> - luacheck warnings of class 6xx refer to whitespace issues and can be ignored. Do not send pull requests "fixing" trailing whitespaces.
> 
> **Rationale**: Git is paranoid about trailing whitespace due to the patch-file email-based workflow inherited from the Linux kernel mailing list. When using the Git tool proper, exceeding whitespace makes no difference whatsoever except for being highlighted by Git's coloring (for the aforementioned reasons). Git's pedantism about it has spread over the year to the syntax highlighting of many text editors and now everyone says they hate trailing whitespace without being really able to answer why (the actual cause being that tools complain to them about it, for no good reason).

It is not true that the only reason many programmers and linters/programming standards care about trailing whitespace is because of Git's influence or it's history with the Linux kernel mailing list. It is common for programmers to care about the exact details of the text that makes up code files. Being able to come up with a narrative around why anyone started to care about this is irrelevant, what matters are the reasons why it is okay or bad. It is also not true that nobody is really able to answer why trailing whitespace is bad, here is the reason why:

Trailing whitespace is unnecessary, extra code that can safely be deleted, and therefore it should be. Extra anything in code that is not serving some purpose is bad. All code is evil. The best situation is when you can remove some code because it is no longer needed or helpful, as it would then no longer need to be maintained. Just as you would not want to leave extra files or variables lying around, you don't want extra whitespace either. All the text in a code file is code, therefore trailing whitespace is also code and should be removed because it can be. The extra whitespace takes up extra storage space for no reason. It is extra characters being uploaded every time the file gets uploaded. It is extra characters getting downloaded every time the file is downloaded. It is extra characters being copied every time the file is copied. Having trailing whitespace makes the `End` key less useful in some editors when you press it for the purpose of quickly getting to the end of the line for the purpose of adding or editing code there because in some editors this will go to the end of the line after the trailing whitespace and then you have to waste time and energy unexpectedly having to delete some trailing whitespace that shouldn't have been allowed to be there to begin with before you can make your useful edit. To illustrate the truthfulness of this, would you be happy if you later discovered that one of the pull requests you accepted had 50,000 trailing whitespaces at the end of each line? If you choose to allow some trailing whitespace, then you need to decide how many are allowed before it is too many. But if you are going to have a rule to consider some amount of trailing whitespace to be too much anyways, you may as well not allow any trailing whitespace. Otherwise it would be a very arbitrary number when you could have just set it the ideal of no trailing whitespace allowed.

**Comment by alerque** [comment]
All true, but there are even more reasons.

* Trailing spaces can even be a security risk when used to obfuscate malicious code. Allowing them in some places opens the door to them being used to hide things in diffs, especially in GitHub PRs.

* Just like for leading whitespace (indentation) there are reasons to normalize. Mixing tabs and spaces and occasionally changing them up causes issues for diffs, code review, bisecting, etc. Normalizing on *not having* trailing whitespace early avoids problems with it down the road.

**Comment by hishamhm** [comment]
@still-dreaming-1 Dude, chill.

There's no reason to drive-by into someone's project and leave a wall of text detailing all the reasons why you think they need to change the way they do things.

This repo only exists because people asked me to write down the style _I_ use when coding the project I've been maintaining pretty much single-handedly for the major part of like 15 years. This is not meant to be an advocacy page to persuade any other project to adopt it. This repo shouldn't even have an "issues" page (it used to be impossible to disable them, but I just saw that Github now allows it), this is not meant to be a big Greek agora where everyone comes together to discuss their opinions on coding style.

And all I said is that I don't want PRs "fixing" whitespace.

> All code is evil.

Gosh. Let's fix this by deleting the whole freakin' project then. Way to motivate people to put their time into open source. Jeez.

**Comment by still-dreaming-1** [comment]
> And all I said is that I don't want PRs "fixing" whitespace.

That is not all you said. You tried to come up with a rationalization for why trailing whitespace should be allowed and why people that think otherwise are wrong. You made claims that people have no good reasons to be against trailing whitespace and could not explain themselves and this was nothing more than leftover, irrelevant, historical influence. The expression "All code is evil" is a term that people who are into clean code and refactoring like. It isn't intended to devalue code or coders or open source code. The point is that if you can solve the same problem in an a better way with less or no code, then that is clearly a superior solution.

The wall of text was my way of thoroughly explaining myself. If I make a claim that something is wrong, but don't bother to explain why or how, or if my explanation is lacking, then that would be extremely rude of me. It would be like saying I'm right just because I say I am and my merely saying it is enough to make other people's viewpoints entirely irrelevant.
